In [5]:
import numpy as np

In [7]:
my_lst = [1,2,3,4]
arr = np.array(my_lst)
print (my_lst)

[1, 2, 3, 4]


In [8]:
type (arr)

numpy.ndarray

In [10]:
arr.shape

(4,)

In [13]:
my_lst1 = [1,2,3,4]
my_lst2 = [4,5,6,7]
my_lst3 = [7,8,9,10]
arr=np.array([my_lst1, my_lst2, my_lst3])

In [14]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [16]:
arr.shape

(3, 4)

In [17]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [18]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [19]:
print(arr)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [20]:
arr[2]

array([ 7,  8,  9, 10])

In [22]:
arr[0:,:]

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [23]:
arr[1:,2:]

array([[ 6,  7],
       [ 9, 10]])

In [24]:
newarr = np.arange(1,300, step = 2)
print (newarr)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299]


In [25]:
arr1 = newarr.copy()

In [26]:
print(arr1)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299]


In [29]:
val = 200
arr1[arr1<val]

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199])

In [30]:
arr1*3

array([  3,   9,  15,  21,  27,  33,  39,  45,  51,  57,  63,  69,  75,
        81,  87,  93,  99, 105, 111, 117, 123, 129, 135, 141, 147, 153,
       159, 165, 171, 177, 183, 189, 195, 201, 207, 213, 219, 225, 231,
       237, 243, 249, 255, 261, 267, 273, 279, 285, 291, 297, 303, 309,
       315, 321, 327, 333, 339, 345, 351, 357, 363, 369, 375, 381, 387,
       393, 399, 405, 411, 417, 423, 429, 435, 441, 447, 453, 459, 465,
       471, 477, 483, 489, 495, 501, 507, 513, 519, 525, 531, 537, 543,
       549, 555, 561, 567, 573, 579, 585, 591, 597, 603, 609, 615, 621,
       627, 633, 639, 645, 651, 657, 663, 669, 675, 681, 687, 693, 699,
       705, 711, 717, 723, 729, 735, 741, 747, 753, 759, 765, 771, 777,
       783, 789, 795, 801, 807, 813, 819, 825, 831, 837, 843, 849, 855,
       861, 867, 873, 879, 885, 891, 897])

In [34]:
np.ones(4)
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.random.rand(5,3)

array([[0.59920863, 0.40593168, 0.18947414],
       [0.30797129, 0.32149446, 0.74499777],
       [0.67453393, 0.48800671, 0.51323308],
       [0.27021694, 0.20267281, 0.24182087],
       [0.92189597, 0.79913689, 0.16341152]])

In [42]:
np.random.randint(0,100, 9).reshape(3,3)

array([[73, 69, 86],
       [ 5, 33,  5],
       [34, 86, 50]])